### ISSUE TITLE
Incoherent description for eglSwapBuffers() in sdk/docs/man

### ISSUE THREAD

**Issue by tchebb** [KhronosGroup/EGL-Registry#103]
The DocBook description of this function seems to have experienced an editing error in the last spec update. Its first sentence [currently reads](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglSwapBuffers.xhtml)
> If *surface* is a back-buffered window surface, **eglSwapBuffers** then the color buffer is copied (posted) native window associated with that surface.

which is not grammatical. For comparison, the EGL 1.5 PDF specification (`specs/eglspec.1.5.pdf`) reads
> If *surface* is a back-buffered window surface, then the color buffer is copied
to the native window associated with that surface.

which makes much more sense.

**Comment by oddhack** [comment]
Thanks! Fixed.
