### ISSUE TITLE
Access to past public EGL registry SVN history is forbidden.

### ISSUE THREAD

**Issue by jolivain** [KhronosGroup/EGL-Registry#104]
Hi,

The EGL-Registry page at:
https://github.com/KhronosGroup/EGL-Registry/blob/master/README.md
mention that:
"
In the past, the EGL registry was maintained in a public Subversion repository. The history in that repository has not been imported to github, but it is still available at https://cvs.khronos.org/svn/repos/registry/trunk/public/egl/ .
"

When clicking on the svn link, I get a login popup. I do have a Khronos user account. When entering my credentials, I get a HTTP 403 forbidden error. Not entering credentials gives a HTTP 401 unauthorized error.

For info, with my Khronos account, I can still navigate in the registry trunk:
https://cvs.khronos.org/svn/repos/registry/trunk/

How can I access to the older EGL Registry history?

Thanks!

Julien.

**Comment by oddhack** [comment]
@outofcontrol may have migrated the server recently, although I don't recall the details. There was supposed to be a redirect which may be failing. James, can you comment here?

**Comment by outofcontrol** [comment]
Access should be fine, however there is no egl folder in public:
https://cvs.khronos.org/svn/repos/registry/trunk/public/

The only APIs showing are gles, glsc, spir-v, typedarray, vx and webcl.

Jon, was EGL removed at some point?

**Comment by oddhack** [comment]
> Jon, was EGL removed at some point?

Possibly? It ought to be there somewhere in SVN history if so. Maybe go to the root of /public and do an SVN log to determine what range of commits is there, then should be able to bisect to where public/egl still exists.

I'm unsure if there's anything of real value in there though. The EGL registry is close to strictly additive - minor updates to extensions get made, new extensions added.

**Comment by jolivain** [comment]
> I'm unsure if there's anything of real value in there though. The EGL registry is close to strictly additive - minor updates to extensions get made, new extensions added.

This history has some value, to know when a given extension/symbol was added.

In some very specific cases, where a recent code base needs to compile with a wide range of gpu drivers (shipping old or recent eglext.h), we may want to work around with code constructs like:

    #if EGL_EGLEXT_VERSION >= 20190808
    /* ... */
    #endif

It's also the case with some unofficial extensions (declared in vendor specific headers like eglmesaext.h or eglextchromium.h) that eventually become official at some point.

Having this history available would helps to easily know exactly what to test.

**Comment by 1ace** [comment]
You shouldn't be testing time stamps or versions but features, eg. `#ifdef EGL_WL_bind_wayland_display`

**Comment by oddhack** [comment]
@outofcontrol if I go to https://cvs.khronos.org/svn/repos/registry/trunk/public/egl/extensions/ I do see the history. The only thing that occurs to me is that the non-logged-in public access might need to be updated as the SVN repo got relocated a while back, IIRC. I can't view this from a non-logged-in browser without putting in my Khronos login, but if I am logged in, I can see the old content here at SVN revision 34076.

**Comment by outofcontrol** [comment]
https://cvs.khronos.org/svn/repos/registry/trunk/public/egl/* is now publicly visible.

**Comment by jolivain** [comment]
I confirm it's working.  I tested with the command:

    svn log --diff https://cvs.khronos.org/svn/repos/registry/trunk/public/egl/api/EGL/eglext.h

Thanks!

**Comment by oddhack** [comment]
@outofcontrol really everything under registry/trunk/public should be publicly visible, not just egl/, to help avoid this coming up again.
