### ISSUE TITLE
EGL_CHROMIUM_sync_control extension missing from EGL-Registry

### ISSUE THREAD

**Issue by pasikarkkainen** [KhronosGroup/EGL-Registry#115]
It seems for some reason "EGL_CHROMIUM_sync_control" extension is missing from the registry. Specification is available at https://chromium.googlesource.com/chromium/src/gpu/+/master/GLES2/extensions/CHROMIUM/EGL_CHROMIUM_sync_control.txt

At least Mesa implements EGL_CHROMIUM_sync_control extension since 2014, and for example Firefox is planning to start using it with the (recently introduced) EGL/X11 backend (https://bugzilla.mozilla.org/show_bug.cgi?id=1640779). Chromium afaik already uses it. There are probably other users aswell.

**Comment by rmader** [comment]
For the record: it may make sense to rename it to `EGL_ANGLE_sync_control` to match `EGL_ANGLE_sync_control_rate` (https://github.com/KhronosGroup/EGL-Registry/issues/116)

**Comment by oddhack** [comment]
We don't include extensions in the registry unless the authors ask for them to be included. Given the age of the extension, it was probably done internally at that time and the author simply didn't realize, or forgot to submit it here, then moved on to other things. The only identified contact is Stéphane Marchesin and if you want to reach out to them, or to the Chromium project, and ask them to submit the extension here, that would be great.

**Comment by stonesthrow** [comment]
👍

**Comment by pasikarkkainen** [comment]
I managed to contact Stéphane Marchesin who is marked as the contact for EGL_CHROMIUM_sync_control extension in the spec. This is the response I got:
```
For Chrome OS (which is what I work on, and why this extension was made),
we have stopped using sync_control circa 2015, when Chrome OS moved all
the WSI stuff outside of the driver. Now we use external eglimages as our
render targets, and then take those buffers to DRM/KMS directly to display
them. In other words, we don't use eglSwapBuffers and friends, and as such
we don't have a need for this extension because we do our own frame
scheduling directly on the display driver.
```

EGL_CHROMIUM_sync_control extension is marked as "Related" in another recently merged EGL_ANGLE_sync_control_rate extension ( https://github.com/KhronosGroup/EGL-Registry/blob/master/extensions/ANGLE/EGL_ANGLE_sync_control_rate.txt ). So for completeness it would of course be good to have EGL_CHROMIUM_sync_control spec merged aswell, but it sounds like google does not have interest for the extension anymore..

**Comment by oddhack** [comment]
> ... so for completeness it would of course be good to have EGL_CHROMIUM_sync_control spec merged aswell, but it sounds like google does not have interest for the extension anymore..

Realistically all that can be done is to create a stub extension specification quoting what you've learned here, in case someone raises the question in the future, and likewise create a stub extension interface in egl.xml (or an actual extension if the API is known from their SDKs). If you want to make a PR along those lines I think it would be accepted -  you would want to include a disclaimer in the "specification" saying that it is not an official Google submission, just a community attempt to document the old extension. We have a few GL extension specs like that already.

**Comment by stonesthrow** [comment]
Checking back, is this issue ready for closure? or do you have action?

**Comment by pasikarkkainen** [comment]
Well, as it seems the original authors are not interested in creating a PR for this, i guess I can copy the extension spec from https://chromium.googlesource.com/chromium/src/gpu/+/refs/heads/main/GLES2/extensions/CHROMIUM/EGL_CHROMIUM_sync_control.txt and create a PR here, with the notes @oddhack mentioned..

I won't have time for this right now, but hopefully I will have before not too long from now.
Thanks for pinging @stonesthrow

**Comment by stonesthrow** [comment]
I'll leave open for you to follow up then.

**Comment by stonesthrow** [comment]
ANGLE has both extensions in angle/extensions.
The EGL registry has [EGL_ANGLE_sync_control_rate.txt](https://github.com/KhronosGroup/EGL-Registry/blob/main/extensions/ANGLE/EGL_ANGLE_sync_control_rate.txt)
So its up to Chromium if EGL_CHROMIUM_sync_control is added to the registry.
If this is not important, then lets close this issue.

**Comment by pasikarkkainen** [comment]
It seems we don't have any EGL_CHROMIUM extensions in EGL-Registry so far. 

Thus I'm not sure if I'm allowed to copy and add "EGL_CHROMIUM_sync_control" extension myself, as that would introduce the whole CHROMIUM directory.. what's the policy on that? Does the directory need to be added by someone from CHROMIUM ?

Would be good if someone from CHROMIUM did this, but I guess they haven't been interested in having their extensions in EGL-Registry ..

**Comment by stonesthrow** [comment]
It would be totally up to the Chromium team, whether they want to add/expose extensions to the registry or not. I can try and contact someone, but since they have not published any extensions, I would think that is their policy. 
Let me ask a few Googlers on the Chromium team and see if there is a policy. But neither I or you should because its a vendor purview.

**Comment by stonesthrow** [comment]
"The ANGLE policy is to skip upstreaming extensions unless we determine it's needed for other teams (outside Google generally)." 

- I will use this as Chromium policy. So no Chromium extensions will be expected.
So this issue can be closed and will not fix.

**Comment by stonesthrow** [comment]
Will not add extension to registry per Chromium policy.
