### ISSUE TITLE
EGL_ANGLE_sync_control_rate extension missing from EGL-Registry

### ISSUE THREAD

**Issue by pasikarkkainen** [KhronosGroup/EGL-Registry#116]
It seems for some reason "EGL_ANGLE_sync_control_rate" extension is missing from the registry. Specification is available at https://chromium.googlesource.com/chromium/src/gpu/+/master/GLES2/extensions/ANGLE/EGL_ANGLE_sync_control_rate.txt

Work is ongoing to implement EGL_ANGLE_sync_control_rate in Mesa (issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/2930 , mr: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5139 ). 

Firefox is currently planning to start using EGL_ANGLE_sync_control_rate with the (recently introduced) EGL/X11 backend ( https://bugzilla.mozilla.org/show_bug.cgi?id=1640779 ).

**Comment by oddhack** [comment]
Same comment as #115, please reach out to the authors and ask them to submit the extension to the registry.

**Comment by stonesthrow** [comment]
👍

**Comment by stonesthrow** [comment]
@jonahr@google.com

**Comment by pasikarkkainen** [comment]
Jonah submitted PR for this, thanks a lot! https://github.com/KhronosGroup/EGL-Registry/pull/118

**Comment by pasikarkkainen** [comment]
@oddhack Any chance you could review PR https://github.com/KhronosGroup/EGL-Registry/pull/118 ? Or perhaps @nwnk ? Thanks!

**Comment by pasikarkkainen** [comment]
Thanks a lot everyone! I'll close this issue as the EGL_ANGLE_sync_control_rate extension spec is now merged.
