### ISSUE TITLE
eglCreatePlatformWindowSurface EGL_GL_COLORSPACE default value

### ISSUE THREAD

**Issue by pauloAndroid** [KhronosGroup/EGL-Registry#125]
For eglCreatePlatformWindowSurface the attribute EGL_GL_COLORSPACE default value is EGL_GL_COLORSPACE_LINEAR in the pdf reference, but EGL_GL_COLORSPACE_SRGB in the web reference.
- https://www.khronos.org/registry/EGL/specs/eglspec.1.5.pdf
- https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglCreatePlatformWindowSurface.xhtml

**Comment by stonesthrow** [comment]
Jon, looks like man page is not matching the spec on the GL_COLORSPACE attribute.
Please fix man page. thx.

**Comment by oddhack** [comment]
Fixed. Note that it may take a little while for the git fix to propagate to the khronos.org/registry/EGL registry.

**Comment by stonesthrow** [comment]
Thanks oddhack.
