### ISSUE TITLE
Upcoming renaming of master -> main branch planned for late August 2021

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/EGL-Registry#131]
@stonesthrow and other interested parties: heads-up that we propose to rename the default branch of this repository to 'main' in late August 2021, following emerging Khronos & github practice (for Khronos members, see internal khronos-general issue 106). This will have very little impact, although if you have a checked-out repository clone, you may want to follow the simple instructions github will pop up on the repository webpage describing how to do the same locally.

If there is a concern about this, please raise it here by 2021-08-23.

**Comment by stonesthrow** [comment]
I will update a small bit of documentation when this is complete.

**Comment by oddhack** [comment]
Default branch has been renamed to master. Let me and @outofcontrol know of any problems.

**Comment by stonesthrow** [comment]
Wiki with instructions has been updated
