### ISSUE TITLE
how can I build and install EGL-Registry on linux os ? 

### ISSUE THREAD

**Issue by GitSoftwareNow** [KhronosGroup/EGL-Registry#135]

**Comment by GitSoftwareNow** [comment]
#ls
api  CODE_OF_CONDUCT.md  extensions  index.php  README.md  registry.tcl  sdk  specs

there is no Makefile here

**Comment by oddhack** [comment]
This repo is primarily a backing store for khronos.org/registry/EGL/ . There is api/Makefile which can be used to regenerate the headers, although there's little reason for most developers to need to do that since they more than likely came packaged with whatever EGL implementation you're using.

**Comment by stonesthrow** [comment]
Question resolved?
