### ISSUE TITLE
Broken link on start.html page

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/EGL-Registry#136]
On this page (https://www.khronos.org/registry/EGL/sdk/docs/man/html/start.html) the link to eglIntro (https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglIntro.html) is broken.

**Comment by stonesthrow** [comment]
Does this need to be reassigned to Richard?

**Comment by KhronosWebservices** [comment]
Would changing the path from:

    https://registry.khronos.org/EGL/sdk/docs/man/html/eglIntro.html

to

    https://registry.khronos.org/EGL/sdk/docs/man/xhtml/eglIntro.html

which resolves the issue, be the correct change?

**Comment by stonesthrow** [comment]
I think that is correct. Jon can confirm.
This is old, so I just thought we can close this with a easy fix.

**Comment by outofcontrol** [comment]
This PR https://github.com/KhronosGroup/EGL-Registry/pull/196 should solve the issue.

**Comment by stonesthrow** [comment]
Thank you. Sorry I cross wired your name with a Richard I know.

**Comment by outofcontrol** [comment]
No worries, though I was going to ask who Richard was :) I will leave it to @oddhack to approve the PR.

**Comment by stonesthrow** [comment]
https://github.com/KhronosGroup/EGL-Registry/pull/196 merged.
This can be closed
