### ISSUE TITLE
EGL_EXT_gl_colorspace_display_p3 gives 404

### ISSUE THREAD

**Issue by janharaldfredriksen-arm** [KhronosGroup/EGL-Registry#15]
The link from https://www.khronos.org/registry/EGL/ gives a 404 for EGL_EXT_gl_colorspace_display_p3*. The spec text as a "EGL_" prefix, but the URL doesn't.'

@courtney-g, @oddhack

**Comment by oddhack** [comment]
I think #16 closed this.
