### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by Eric-JH** [KhronosGroup/EGL-Registry#162]
I did install `libegl1-mesa` and `libegl1-mesa-dev` on my ubuntu platform. But when I run the sample code from [nvdiffrast](https://nvlabs.github.io/nvdiffrast/), there is a error and reports `/usr/bin/ld: cannot find -lEGL`. How can I fix this plz?

**Comment by 1ace** [comment]
`libEGL.so` is provided by the package `libegl1` on ubuntu :wink:

**Comment by Eric-JH** [comment]
I failed to install libegl1. `Package libegl1 is not available, but is referred to by another package.This may mean that the package is missing, has been obsoleted, or is only available from another source` was reported. I googled the problem. I'm sure my config file of `apt` is correct. And command `apt-cache search libegl1` feed me other parties instead of libegl. So what can I do with this situation?

**Comment by stonesthrow** [comment]
Developer boards for community help are usually the best place for these questions.

**Comment by 1ace** [comment]
As @stonesthrow said, this isn't a support forum, but beyond that, since your issue is about using Ubuntu, you might be best served by asking Ubuntu people for help; their two main websites are https://askubuntu.com and https://ubuntuforums.org

**Comment by Eric-JH** [comment]
I got it. Thanks for all
