### ISSUE TITLE
eglCreateContext attrib_list documentation is confusing

### ISSUE THREAD

**Issue by vvavrychuk** [KhronosGroup/EGL-Registry#166]
https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreateContext.xhtml attrib_list parameter explanation says

> Only the attribute EGL_CONTEXT_CLIENT_VERSION may be specified.

Word `may` looks like a typo, since in `eglCreateContext` function description a lot more attributes are mentioned which **may** be specified.

**Comment by stonesthrow** [comment]
Agreed this sentence  is funny given the list of allowed attributes.

I suggest we remove this "Only the attribute EGL_CONTEXT_CLIENT_VERSION may be specified."

**Comment by stonesthrow** [comment]
Thanks @vvavrychuk . I will make a change and have it reviewed per EGL process.

**Comment by vvavrychuk** [comment]
Thanks @stonesthrow for quick feedback!
