### ISSUE TITLE
eglCreatePlatform{Window,Pixmap}Surface documentation should mention EGL 1.5 dependency

### ISSUE THREAD

**Issue by RAOF** [KhronosGroup/EGL-Registry#169]
As far as I can tell these entry points are new in EGL 1.5 (folded in from the `EGL_EXT_platform_base` extension in 1.4). The `eglGetPlatformDisplay` correctly mention that it's new in 1.5, but neither the `eglCreatePlatformWindowSurface` nor `eglCreatePlatformPixmapSurface` docs do (instead they somewhat-misleadingly document some of their accepted parameter values as new in 1.5).

I can prepare a PR to update the docs if I've understood this correctly.

**Comment by stonesthrow** [comment]
As I recall, yes, they were extension in EGL 1.4 and then with EGL 1.5 they were accepted as core API.
Yes, Please point out the inconsistent/misleading text for correction. thx.

**Comment by stonesthrow** [comment]
Of course, the names of functions and tokens will change - dropping "EXT" or "KHR" when adopted into core.
