### ISSUE TITLE
Query context reset notification strategy

### ISSUE THREAD

**Issue by bl4ckb0ne** [KhronosGroup/EGL-Registry#184]
With the extension `EGL_EXT_create_context_robustness` [1], it is possible to specify the reset notification strategy of a context by adding two fields in the attribute list when using `eglCreateContext`.

Unfortunately, it is not possible to query the reset notification strategy of a given context. When trying to get the `EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT` with `eglQueryContext`, `EGL_BAD_ATTRIBUTE` is returned, despite the requested attribute being valid.

This comes in the way when trying to create a shared context of a context with a specific reset notification strategy. From the `EGL_EXT_create_context_robustness` spec changes:

      If the reset notification behavior of <share_context> and the
      newly created context are different then an EGL_BAD_MATCH error is
      generated.

Is this an implementation details, and Mesa (the driver I am using) could returns the correct value instead of `EGL_BAD_ATTRIBUTE`, or is this a whole in the spec waiting to be defined and improved?

[1]: https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_create_context_robustness.txt

**Comment by stonesthrow** [comment]
Check GL_EXT_robustness - this looks to provide the query:

    Returned by GetIntegerv and related simple queries when <value> is
    RESET_NOTIFICATION_STRATEGY_EXT :
        LOSE_CONTEXT_ON_RESET_EXT                       0x8252
        NO_RESET_NOTIFICATION_EXT                       0x8261

**Comment by bl4ckb0ne** [comment]
Completely missed it, thanks. Is it normal that the values between GL and EGL don't match?

```
/usr/include/EGL/eglext.h:662:#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT 0x3138
/usr/include/GLES/glext.h:693:#define GL_RESET_NOTIFICATION_STRATEGY_EXT 0x8256
/usr/include/GLES2/gl2ext.h:1729:#define GL_RESET_NOTIFICATION_STRATEGY_EXT 0x8256
```

**Comment by oddhack** [comment]
It is more common that they do not match, but there are some exceptions.

**Comment by bl4ckb0ne** [comment]
Would an edit to the EGL extension to add the value to `eglQueryContext` be accepted? In some cases the EGL code is seperated from the GL code, and pulling the two headers to get a single value is annoying.

**Comment by oddhack** [comment]
For an already shipping extension (13 years!) we cannot change enum values. That would break the ABI.

**Comment by dgkoch** [comment]
> Not changing the values, adding `EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT` to `eglQueryContext` instead of returning `EGL_BAD_ATTRIBUTE`.
> 

That's still changing an extension that has been shipping for 12 or 13 years without this functionality.

**Comment by oddhack** [comment]
It would have to be proposed as a new extension, probably an EXT. Specifying the behavior is easier than getting implementers to *support* the extension, though. If you just need it in Mesa, then you might be able to work with them to define a MESA or EXT extension. It sounds straightforward to implement, it's rollout that's challenging.

**Comment by oddhack** [comment]
You would need to work with the Mesa project to specify such an extension and produce an implementation they will accept into their release, but I do not know details of that.

It would probably make more sense as an EXT if there's any interest  from other EGL implementers, since there's nothing Mesa-specific about it.

**Comment by bl4ckb0ne** [comment]
Thanks. I'm about to start drafting the ext, I'll start with the EXT prefix and change it after if nobody shows interest in the meantime.
