### ISSUE TITLE
Wrong EGL native types used for QNX

### ISSUE THREAD

**Issue by jmcdonnell-blackberry** [KhronosGroup/EGL-Registry#191]
On QNX, \_\_unix\_\_ is also defined.  Since the \_\_unix\_\_ block appears before the \_\_QNX\_\_ block, the Unix native types are chosen rather than the QNX native types.  The \_\_QNX\_\_ block needs to precede the \_\_unix\_\_ block.

The \_\_QNX\_\_ block also needs to precede the WL_EGL_PLATFORM block.  The existence of WL_EGL_PLATFORM doesn't necessarily indicate that Wayland is the native window platform.  It only indicates that Wayland is a supported platform.  For QNX, QNX Screen is currently the native window platform but Wayland may also be a window platform (accessed via eglGetPlatformDisplay, et al).

Really, it would be better if the native window platform was explicitly defined rather than being guessed.  But that's probably something that can't be changed at this point.

**Comment by stonesthrow** [comment]
Agreed, __unix__ should be last in the if-else sequence. Sorry we missed this.

It can be conflated, eglPlatform.h should be only indicating the default. That reordering seems OK.

I think it was supposed that the compiler would know the platform and and the macro set. But with multiple support there maybe many combinations of which goes first.

Do you want to propose a change to eglPlatform.h? The MR should be limited to just this change.

**Comment by jmcdonnell-blackberry** [comment]
Yes, I can propose a change.

**Comment by stonesthrow** [comment]
The __unix__ seems like its a catch all for any undefined window system on a linux/unix platform. Jon may remember some history on this.

**Comment by oddhack** [comment]
I have a vague recollection of initially using some comparable set of ifdefs from Mesa headers. That was a *long* time ago.

**Comment by stonesthrow** [comment]
I think we'll need a couple of reviewers, so to check that we haven't inadvertently broke some platform. Especially around QNX, Wayland, Unix. where the change will touch.

**Comment by stonesthrow** [comment]
https://github.com/KhronosGroup/EGL-Registry/pull/192 is merged.
Closing issue
