### ISSUE TITLE
Discover lack of implicit synchronization support

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/EGL-Registry#207]
Some drivers (e.g. NVIDIA proprietary driver on Linux) don't support implicit synchronization.

Add a way to query implicit synchronization support so that EGL users can figure out whether they need explicit synchronization or `eglFinish()`.

cc @cubanismo

**Comment by stonesthrow** [comment]
Got a proposal idea? Specific window systems? Wayland?

**Comment by emersion** [comment]
AFAIK the driver doesn't support implicit sync on any windowing system. This is not an issue when using `EGLSurface` since the driver can take care of doing an implicit `eglFinish()` during `eglSwapBuffers()`. This is an issue for `EGLImage` where `eglFlush()` indicates an implicit sync point. (Should it be the responsibility of the driver to make that an implicit `eglFinish()` call instead?)

A simple solution would be to expose an informational extension `EGL_no_implicit_sync` which indicates lack of implicit sync.

**Comment by stonesthrow** [comment]
This discussion from OpenGl ES, form a while back about sync with Images.
https://github.com/KhronosGroup/OpenGL-Registry/issues/566
In general the state of an image is responsibility of app, and should use syncs when modifying/sharing. But, there are cases such as binding to texture that have an implicit flush.

**Comment by cubanismo** [comment]
Agreed. Implicit sync is a Linux-ism, outside the scope of EGL/OpenGL. EGL/OpenGL has always required explicit sync. Some Linux drivers just decided to make things work when apps relied on what is officially undefined behavior from an EGL/OpenGL POV. If you want to add an extension like EGL_SOMETHING_no_synchronization_required that is only present on those drivers, fine by me, but officially OpenGL requires explicit sync, so I don't think we need anything extra to say explicit sync is required.

**Comment by emersion** [comment]
Alright. Implicit sync is the norm on Linux, so I don't think it makes sense to have an EGL extension to advertise it. I'll just leave things as-is, with a glitchy result on drivers lacking explicit sync. Thanks for the feedback!
