### ISSUE TITLE
khronos_stime_nanoseconds_t in egl.xml

### ISSUE THREAD

**Issue by lawadr** [KhronosGroup/EGL-Registry#34]
The **khronos_utime_nanoseconds_t** type is declared in egl.xml on the following line:
`<type name="khronos_utime_nanoseconds_t" requires="khrplatform"/>`

However, **khronos_stime_nanoseconds_t** isn't. The following line needs to be added:
`<type name="khronos_stime_nanoseconds_t" requires="khrplatform"/>`

Currently this is breaking my code generation.

**Comment by oddhack** [comment]
Done.
