### ISSUE TITLE
Build breakages on Mac OS X due to X11 header dependency

### ISSUE THREAD

**Issue by c0d1f1ed** [KhronosGroup/EGL-Registry#52]
#43 made eglplatform.h include X11 headers on __APPLE__ platforms. Unfortunately this breaks building Chrome because these headers are not readily available. Also note that the PowerVR SDK has been using int type for EGLNativeDisplayType (0 to indicate the default display), and NSView* for EGLNativeWindowType (cast to void*), since at least 2010.

So I don't think EGL should suddenly demand using X11 on Mac OS X. @1ace can we make it optional? Something like USE_X11, similar to the existing USE_OZONE, would work for us. Open to other suggestions.

**Comment by 1ace** [comment]
If you're using the headers [provided by Mesa](https://cgit.freedesktop.org/mesa/mesa/tree/include/EGL/eglplatform.h), you can use `MESA_EGL_NO_X11_HEADERS`.

We could push this up to Khronos as a `USE_X11`; what do you think @oddhack?
I'm on my way home right now, I'll look at this tomorrow.

**Comment by oddhack** [comment]
@1ace if the problem is that the X11 dependency is causing breakage on Apple, maybe the symbol should be opt-in instead of opt-out, so that people not using X11 before don't have to do something extra? That's all I can think of.

**Comment by stonesthrow** [comment]
Do this? make section for APPLE with old definition: (Does this work for APPLE/CHROME?)

```
#elif defined(__APPLE__)

typedef int   EGLNativeDisplayType;
typedef void *EGLNativeWindowType;
typedef void *EGLNativePixmapType;

#elif defined(__unix__)

/* X11 (tentative)  */
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef Display *EGLNativeDisplayType;
typedef Pixmap   EGLNativePixmapType;
typedef Window   EGLNativeWindowType;

```

**Comment by c0d1f1ed** [comment]
@stonesthrow that basically reverts #43 and thus would work for Chrome but would break Mesa's use of X11 on Mac OS. As noted above there should be an opt-in for that, using a macro like `USE_X11`.

I checked that on Max OS X `__APPLE__` is defined but not `__unix__`, so we can do:
```
#elif defined(__unix__) || defined(USE_X11)

/* X11 (tentative)  */
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef Display *EGLNativeDisplayType;
typedef Pixmap   EGLNativePixmapType;
typedef Window   EGLNativeWindowType;

#elif defined (__APPLE__)

typedef int   EGLNativeDisplayType;
typedef void *EGLNativeWindowType;
typedef void *EGLNativePixmapType;
```

The Symbian defines could potentially join the `__APPLE__` case again, but I don't think it's worth the risk for the minor saving in lines of code, and it makes things clearer anyway to keep them separate.

**Comment by stonesthrow** [comment]
I don't have builds for APPLE or Chrome, So if this is verified, and no objections, we can make the proposed changes - need PR.
