### ISSUE TITLE
EGL_DRM_MASTER_FD_EXT is missing in egl.xml and headers

### ISSUE THREAD

**Issue by evelikov** [KhronosGroup/EGL-Registry#57]
While implementing EGL_EXT_device_drm in Mesa I've noticed that the token is missing.
I did not look closely exactly what need to be tweaked, hence this issue instead of a PR.

Might be worth checking the other EGL Device/Output extensions for missing parts.

@dkartch-nv @cubanismo @1ace

**Comment by 1ace** [comment]
I think the token was just forgotten; unless I'm mistaken, everything else from this extension was added.
I've just created PR #58 to fix this.
