### ISSUE TITLE
Inconsistency between EGL 1.4 refpages and EGL 1.4 spec

### ISSUE THREAD

**Issue by matanui159** [KhronosGroup/EGL-Registry#62]
EGL 1.4 reference pages, eglChooseConfig:
> The alpha mask buffer is used only by OpenGL and OpenGL ES client APIs.

EGL 1.4 specification, page 17:
> The alpha mask buffer is used only by OpenVG.

Which one is it? 😛

**Comment by stonesthrow** [comment]
Thanks for identifying the inconsistency. The text in the EGL spec is correct and can be further supported by looking at the OpenVG specification.
We'll correct the online reference manual.
