### ISSUE TITLE
Typo in the description for eglGetCurrentSurface

### ISSUE THREAD

**Issue by kbrenneman** [KhronosGroup/EGL-Registry#66]
In the EGL 1.5 spec, there's a couple minor typos in the description of eglGetCurrentSurface on page 62:

In the line:
> If there is no current context for the current rendering API, then EGL_NO_SURFACE is returned (this is not an error).

That should probably say "If there is no current surface," since in EGL 1.5 you're allowed to have a current context without a current surface.

On the same page, the error description says eglGetCurrentContext where it should say eglGetCurrentSurface, and is missing a period at the end of the first sentence:
> Errors
> eglGetCurrentContext returns EGL_NO_SURFACE on failure (but may
> also return it if no context is bound, as described above)
> If readdraw is neither EGL_READ nor EGL_DRAW , an EGL_BAD_-
> PARAMETER error is generated.

**Comment by 1ace** [comment]
I think this repo is for the extensions and the headers; the spec issues are handled on https://gitlab.khronos.org/egl/API/issues

**Comment by stonesthrow** [comment]
We'll discuss and update as needed.

**Comment by stonesthrow** [comment]
Assigning editor for next update of spec.

**Comment by stonesthrow** [comment]
This issue has been resolved internal to Khronos EGL WG. Text has been corrected in upcoming spec release.
