### ISSUE TITLE
Unable to specify non-linear Display-P3 with no HW transfer function

### ISSUE THREAD

**Issue by courtney-g** [KhronosGroup/EGL-Registry#69]
There are cases where an application may want to apply the sRGB transfer function as part of it's shader computations and would like to use the non-linear Display-P3 color space. However, the current EGL_EXT_gl_colorspace_display_p3 will always use the HW sRGB support for 8-bit pixel formats.

**Comment by oddhack** [comment]
I think #71 should have closed this - if not please reopen and note what remains TBD.
