### ISSUE TITLE
eglChooseConfig returns num_config as zero in QT Creator

### ISSUE THREAD

**Issue by lasithitfac** [KhronosGroup/EGL-Registry#74]
I am new to EGL and I have to use libEgl.lib on one of my projects. We are using QT Creator as the IDE.
When running the application it returns "num_config" as zero in  eglChooseConfig function. But the same code runs without any issue in visual studio.  Could somebody guide me on this whether there is any dependency  for the EGL library.

**Comment by stonesthrow** [comment]
These kinds of question are usually posted to the Khronos Forum: https://forums.khronos.org/forumdisplay.php/79-EGL 
or stackoverflow
First check if you get return of true or false. False indicates an error and you should call eglGetError() to get further information. True means no match. Provided that "configs" and "config_size" are valid values.

**Comment by pqfeng** [comment]
thank you. @stonesthrow   It just so happened that I also ran into this problem

**Comment by stonesthrow** [comment]
I would guess that the EGL/GL driver library used in Visual Studio might be different than the one used from command line - Since you seem to get a different set of configs.
https://registry.khronos.org/EGL/sdk/docs/man/html/eglChooseConfig.xhtml
https://registry.khronos.org/EGL/sdk/docs/man/
