### ISSUE TITLE
EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage

### ISSUE THREAD

**Issue by Oi-apps** [KhronosGroup/EGL-Registry#83]
The first run of the Android app on emulator  is OK. But after ghranting permission from user to access to the particular activity the emulator craches with the following logs:
3:30 PM	Emulator: queryCoreProfileSupport: swap interval not found

In Android bug report  I found :

05-13 13:28:46.486  1456  1456 I SurfaceFlinger: EGL information:
05-13 13:28:46.486  1456  1456 I SurfaceFlinger: vendor    : Android
05-13 13:28:46.486  1456  1456 I SurfaceFlinger: version   : 1.4 Android META-EGL
05-13 13:28:46.486  1456  1456 I SurfaceFlinger: extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable 
05-13 13:28:46.486  1456  1456 I SurfaceFlinger: Client API: OpenGL_ES
05-13 13:28:46.486  1456  1456 I SurfaceFlinger: EGLSurface: 8-8-8-8, config=0x2
05-13 13:28:46.487  1456  1456 D EGL_emulation: eglCreateContext: 0xb1820960: maj 2 min 0 rcv 2

I can rerun the emulator only after clearing up all emulator's data ( Tools->AVD Manage ->Wipe Data)

video controller data:

  lspci|grep VGA
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
  sudo lshw -C video
 
  *-display UNCLAIMED     
       description: 3D controller
       product: GM107M [GeForce GTX 960M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: latency=0
       resources: memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:df000000-df07ffff
  *-display
       description: VGA compatible controller
       product: HD Graphics 530
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:129 memory:dd000000-ddffffff memory:b0000000-bfffffff ioport:f000(size=64) memory:c0000-dffff
 

related issues are mentioned here:
https://stackoverflow.com/questions/25281224/android-setswapinterval-interval-1-not-set-when-try-to-open-new-window
https://stackoverflow.com/questions/16285546/glfwswapinterval1-fails-to-enable-vsync

https://community.nxp.com/thread/378756
thus, it may contain more than one item. In my case, I was getting the error: "Failed to choose config, error = EGL_SUCCESS". By changing the line below:
    if (!eglChooseConfig(mEglDisplay, attribs, &mEglConfig, num_configs, &num_configs)             || num_

**Comment by oddhack** [comment]
@Oi-apps this sounds like a problem with the driver or the emulator, which isn't something we can address here. This repo is just a publishing mechanism for specifications, and what you're encountering doesn't seem related to a specification problem. If you agree, please close this; if not, please clarify what you would like us to do with the extension specifications that would help address your issue.

**Comment by oddhack** [comment]
Closing for lack of feedback.
