### ISSUE TITLE
EGL error 0x300c at eglGetDisplay

### ISSUE THREAD

**Issue by winnechan** [KhronosGroup/EGL-Registry#91]
Hi, I have tried to run a 3D Similator in the [repo](https://github.com/peteanderson80/Matterport3DSimulator) on a nvidia-docker container. However, when I ran the unittest which did some rendering jobs, an unusual error was encountered:

> /root/mount/Matterport3DSimulator/src/test/main.cpp:350: FAILED:
> REQUIRE_NOTHROW( sim.initialize() )
> due to unexpected exception with message:
> EGL error 0x300c at eglGetDisplay
> 
> test cases: 5 | 4 passed | 1 failed
> assertions: 119187 | 119186 passed | 1 failed

According to the test code, **I think it is just related to the following code** in [MatterSim.cpp: line169~177](https://github.com/peteanderson80/Matterport3DSimulator/blob/master/src/lib/MatterSim.cpp):   
  
``` 
       // Initialize EGL
        eglDpy = eglGetDisplay(EGL_DEFAULT_DISPLAY);
        assertEGLError("eglGetDisplay");

        EGLint major, minor;

        eglInitialize(eglDpy, &major, &minor);
        assertEGLError("eglInitialize");
``` 

I feel strange that eglGetDisplay rerturns 0x300c and have no idea to solve this problem.
How can I fix it? Do I need to bind some physical display devices to the container or set the environment DISPLAY in the container to let the system access display devices? 

Thx!m

**Comment by stonesthrow** [comment]
This may be unique to NVidia implementation. Asking for a comment.

**Comment by stonesthrow** [comment]
The error returned indicates that EGL_DEFAULT_DISPLAY is not supported or not a valid handle. This seems to be an environment or platform issue. Please check into Stackoverflow to see if you can get specific help. Closing as its not a specification issue,
